NHSDigital/api-management-service-template

- README.md
- azure/azure-build-pipeline.yml
- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
- azure/project.yml
- package-lock.json
- package.json
- proxies/live/apiproxy/policies/KeyValueMapOperations.GetSecureVariables.xml
- proxies/live/apiproxy/policies/KeyValueMapOperations.GetVariables.xml
- proxies/live/apiproxy/proxies/default.xml
- proxies/live/apiproxy/proxy.xml
- proxies/live/apiproxy/targets/target.xml
- proxies/sandbox/apiproxy/policies/KeyValueMapOperations.GetAsid.xml
- proxies/sandbox/apiproxy/proxy.xml
- pyproject.toml
- terraform/main.tf
* Switch over to common pipelines
> Apm 1214 common pipeline

- azure/azure-release-pipeline.yml
Also change 'ref' to 'int' as we don't use ref.
> add 'make_spec_visible' controls and explanation.

- sandbox/Dockerfile
> Apm 000 update sandbox

- .github/workflows/pr-lint.yaml
> APM-1623 Fix jira link too

- .github/workflows/pr-lint.yaml
- proxies/live/apiproxy/policies/KeyValueMapOperations.GetSecureVariables.xml
- proxies/live/apiproxy/policies/RaiseFault.401Unauthorized.xml
- proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
- proxies/live/apiproxy/policies/ServiceCallout.CallSpineHealthcheck.xml
- proxies/live/apiproxy/policies/javascript.SetStatusResponse.xml
- proxies/live/apiproxy/proxies/default.xml
- proxies/live/apiproxy/resources/jsc/SetStatusResponse.js
> APMSPII-403 - added files for status endpoint

- proxies/live/apiproxy/proxies/default.xml
* If left here causes a very unhelpful error when validating that takes 4+ hours to debug
* Moves status flow inside flows block
> APM-1162 Fix status flow placement

- manifest_template.yml
* Add manifest to template repo
> APM-1706 Add initial manifest file

- ecs-proxies-containers.yml
- ecs-proxies-deploy.yml
* remove short service name prefix for ecs definitions
> APM-1910 remove short service name prefix for ecs definitions

- ecs-proxies-deploy.yml
> APm-1910 escape using raw

- proxies/live/apiproxy/resources/jsc/HealthCheck.SetResponse.js
- proxies/sandbox/apiproxy/resources/jsc/HealthCheck.SetResponse.js
> APM-2078 set status.response

- README.md
Fix broken developer hub link on README.md
> apm-2601 Fix developer-hub hyperlink

- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
- manifest_template.yml
Disable sandbox deployment by default
> APM-1714 disable sandbox release by default

- proxies/live/apiproxy/policies/AssignMessage.AddCors.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
Add Access-Control-Expose-Headers in the API proxy template repo - Sandbox
> Added access control expose headers to sandbox

- specification/example.yaml
add standard headings for description
> AMB-1112 improve template spec

- CONTRIBUTING.md
- README.md
Create a practical README file in the API Template repository that covers where files are, and how to use it in "developer terms"
> AMB-1110: update readme to walkthrough folders and files

- proxies/sandbox/apiproxy/proxies/default.xml
Add no route rule for sandbox _status endpoint
> APM-000 add no rute rule for _status endpoint

- azure/azure-release-pipeline.yml
- manifest_template.yml
> APM-3095 Correct environments and make portal visibility configurable

- Makefile
- azure/azure-release-pipeline.yml
- azure/templates/run-tests.yml
* Updating guidance around test-utiles 2.0 to reflect changes made to support smoketests in prod
> APM-3626 update template with guidance

- Makefile
- azure/azure-release-pipeline.yml
- azure/project.yml
- azure/templates/run-tests.yml
> APM-3626 fixed template

- Makefile
- azure/templates/run-tests.yml
> fix prod test cmd

- package-lock.json
- package.json
> remove newman

- specification/example.yaml
> Update example.yaml - add open source sub-section and other tweaks

- manifest_template.yml
> APM-4806: Removing API Catalogue from the manifest as we no longer create these

- manifest_template.yml
> APM-3408 Remove reference to portal visibility and use access attribute
